export default {
  FETCH_TEST: 'FETCH_TEST',
  FETCH_TEST_SUCCESS: 'FETCH_TEST_SUCCESS',
  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
};
